const {GraphQLEnumType} = require('graphql');

module.exports = new GraphQLEnumType({
	name: 'ExerciseTypes',
	values: {
		BARBELL_CURL: {value: 'Barbell Curl'},
		DUMBBELL_CURL: {value: 'Dumbbell Curl'},
		BARBELL_TRICEP_PRESS: {value: 'Barbell Tricep Press'},
		DUMBBELL_TRICEP_PRESS: {value: 'Dumbbell Tricep Press'},
		OVERHEAD_PRESS: {value: 'Overhead Press'},
		WRIST_CURL: {value: 'Wrist Curl'},
		TRICEP_KICKBACK: {value: 'Tricep Kickback'},
		BENCH_PRESS: {value: 'Bench Press'},
		CABLE_CROSSOVER: {value: 'Cable Crossover'},
		DUBBELL_FLY: {value: 'Dumbbell Fly'},
		INCLINE_BENCH: {value: 'Incline Bench'},
		DIPS: {value: 'Dips'},
		PUSHUP: {value: 'Pushup'},
		PULLUP: {value: 'Pullup'},
		BACK_RAISE: {value: 'Back Raise'},
		BENT_OVER_ROW: {value: 'Bent-Over Row'},
		SEATED_ROW: {value: 'Seated Row'},
		CHINUP: {value: 'Chinup'},
		LAT_PULLDOWN: {value: 'Lat Pulldown'},
		SEATED_REVERSE_FLY: {value: 'Seated Reverse Fly'},
		MILITARY_PRESS: {value: 'Military Press'},
		UPRIGHT_ROW: {value: 'Upright Row'},
		FRONT_RAISE: {value: 'Front Raise'},
		SIDE_LATERAL_RAISE: {value: 'Side Lateral Raise'},
		SNATCH: {value: 'Snatch'},
		PUSH_PRESS: {value: 'Push Press'},
		SHRUG: {value: 'Shrug'},
		CRUNCH_MACHINE: {value: 'Crunch Machine'},
		CRUNCH: {value: 'Crunch'},
		AB_TWIST: {value: 'Ab Twist'},
		BICYCLE_KICK: {value: 'Bicycle Kick'},
		HANGING_LEG_RAISE: {value: 'Hanging Leg Raise'},
		HANGING_KNEE_RAISE: {value: 'Hanging Knee Raise'},
		REVERSE_CRUNCH: {value: 'Reverse Crunch'},
		V_UP: {value: 'V Up'},
		SITUP: {value: 'Situp'},
		SQUAT: {value: 'Squat'},
		LUNGE: {value: 'Lunge'},
		DEAD_LIFT: {value: 'Dead Lift'},
		HAMSTRING_CURL: {value: 'Hamstring Curl'},
		GOOD_MORNING: {value: 'Good Morning'},
		CLEAN: {value: 'Clean'},
		LEG_PRESS: {value: 'Leg Press'},
		LEG_EXTENSION: {value: 'Leg Extension'},
		OTHER: {value: 'Other'}
	}
});